digitalmarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from dashboard.views import DashboardView
from checkout.views import CheckoutTestView, CheckoutAjaxView
from products.views import UserLibraryView


urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^seller/', include('sellers.urls', namespace='sellers')),
    url(r'^checkout/$', CheckoutAjaxView.as_view(), name='checkout'),
    url(r'^test$', CheckoutTestView.as_view(), name='test'),
    url(r'^admin/', admin.site.urls),
    # url(r'^$', RedirectView.as_view(url='products/')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^tags/', include('tags.urls', namespace='tags')),
    url(r'^library/', UserLibraryView.as_view(), name='library'),

    ####################### Old function-based views, for reference #################################
    # url(r'^list/$', product_views.list_view, name='list_view'),
    # url(r'^create/$', product_views.create_view, name='create_view'),
    # url(r'^detail/(?P<object_id>\d+)/$', product_views.detail_view, name='detail_view'),
    # url(r'^detail/(?P<object_id>\d+)/edit/$', product_views.update_view, name='update_view'),
    # url(r'^detail/(?P<slug>[\w-]+)/$', product_views.detail_slug_view, name='detail_slug_view'),
    # url(r'^detail/$', product_views.detail_view, name='detail_view')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL)

products/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.ProductListView.as_view(), name='list'),
    url(r'^rate/$', views.ProductRatingAjaxView.as_view(), name='rating'),
    # url(r'^(?P<pk>\d+)/edit/$', views.ProductEditView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.ProductEditView.as_view(), name='edit_slug'),

    url(r'^(?P<pk>\d+)/$', views.ProductDetailView.as_view(), name='detail'),
    # the slug url should be below the PK one, to avoid not found errors
    # because the slug regex will match the PK as well
    url(r'^(?P<slug>[\w-]+)/$', views.ProductDetailView.as_view(), name='detail_slug'),

    url(r'^(?P<pk>\d+)/download/', views.ProductDownloadView.as_view(), name='download'),
    url(r'^(?P<slug>[\w-]+)/download/', views.ProductDownloadView.as_view(), name='download_slug'),
]

tags/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.TagListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', views.TagDetailView.as_view(), name='detail'),
]

billing/models.py
from django.db import models as m
from django.contrib.auth.models import User
from products.models import Product


# Create your models here.
class Transaction(m.Model):

    user = m.ForeignKey(User)
    product = m.ForeignKey(Product)
    price = m.DecimalField(max_digits=100, decimal_places=2)
    timestamp = m.DateTimeField(auto_now_add=True, auto_now=False)
    success = m.BooleanField(default=True)

    # To be added later
    # transaction_id_payment_system = Braintree / Stripe
    # payment_method
    # last_four (digits of the credit card)

    def __str__(self):
        return '{}----{}----{}--{}--{}'.format(self.id, self.timestamp, self.user, self.product, self.product.get_price)

products/models.py
from django.contrib.auth.models import User
from django.db import models as m
from django.db.models.signals import pre_save, post_save

from django.core.urlresolvers import reverse

# imports for generating thumbnails
from django.core.exceptions import MultipleObjectsReturned
from django.http import HttpResponse

# Various functions to make life easier
from . import model_helpers as helpers
from sellers.models import SellerAccount

THUMBNAIL_CHOICES = (
    ('hd', 'HD'),
    ('sd', 'SD'),
    ('micro', 'Micro')
)


############################ Model Classes ##########################
class Product(m.Model):

    # One-to-one mapping example
    # owner = m.OneToOneField(User)

    # Many-to-one mapping
    # owner = m.ForeignKey(User, related_name='product_owner')
    # # Many-to-many mapping
    # managers = m.ManyToManyField(User, related_name='product_managers', blank=True)

    seller = m.ForeignKey(SellerAccount)
    title = m.CharField(max_length=30)
    slug = m.SlugField(blank=True, unique=True)
    description = m.TextField(blank=True)
    media = m.ImageField(blank=True, null=True, upload_to=helpers.media_location)
    price = m.DecimalField(max_digits=100, decimal_places=2, default=9.99)
    sale_price = m.DecimalField(max_digits=100, decimal_places=2, default=6.99, null=True, blank=True)
    on_sale = m.BooleanField(default=False)
    is_available = m.BooleanField(default=True)  # is the product available to purchase?

    def __str__(self):
        return self.title

    # the URL to redirect to upon successful creation of the model instance
    # This will be used for both create and edit views unless overwritten
    def get_absolute_url(self):
        view_name = 'products:detail_slug'
        print('The absolute URL is:', reverse(view_name, kwargs={'slug': self.slug}))
        return reverse(view_name, kwargs={'slug': self.slug})

    def get_edit_url(self):
        view_name = 'sellers:product_edit'
        return reverse(view_name, kwargs={'pk': self.id})

    #  This will provide a download link for the product
    def get_download(self):
        view_name = 'products:download'
        url = reverse(view_name, kwargs={'pk': self.id})
        return url

    @property
    def get_price(self):
        if self.sale_price and self.on_sale:
            return self.sale_price
        return self.price


class Thumbnail(m.Model):
    product = m.ForeignKey(Product)
    # user = m.ForeignKey(User)
    type = m.CharField(max_length=20, choices=THUMBNAIL_CHOICES, default='hd')
    height = m.CharField(max_length=20, null=True, blank=True)
    width = m.CharField(max_length=20, null=True, blank=True)
    media = m.ImageField(
        height_field='height', width_field='width',
        blank=True, null=True, upload_to=helpers.thumbnail_location)

    def __str__(self):
        # This effectively returns product slug + thumbnail filename
        return self.media.name


class MyProducts(m.Model):
    user = m.OneToOneField(User)
    products = m.ManyToManyField(Product, blank=True)

    def __str__(self):
        # Get titles of all products the user owns
        product_titles = [product.title for product in self.products.all()]

        # Make a string out of them
        product_list = product_titles[0]
        for product in product_titles[1:]:
            product_list = product_list + ', ' + product
        product_set = '{} - {}'.format(str(self.user).capitalize(), product_list)
        return product_set

    # This allows to change the names used in Admin section :)
    class Meta:
        verbose_name = 'My Products'
        verbose_name_plural = 'My Products'


class ProductRating(m.Model):
    user = m.ForeignKey(User)
    product = m.ForeignKey(Product)
    rating = m.IntegerField(null=True, blank=True)
    verified = m.BooleanField(default=False)

    def __str__(self):
        return "{}-{}-{}".format(self.product, self.rating, self.user)

###################################### Signal Functions ######################################
# this can be used to manipulate data before saving it to DB!
def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = helpers.create_unique_slug(Product, instance)
        print('Added slug {} to instance {}'.format(instance.slug, instance))

pre_save.connect(product_pre_save_receiver, sender=Product)


# This could be use to notify other parts of the app when a new item has been added to DB
def product_post_save_receiver(sender, instance, created, *args, **kwargs):
    print('Product has been saved with ID {}'.format(instance.id))

    if instance.media:
        try:
            # .get_or_create method returns a tuple
            # 1st item is an object itself
            # 2nd is boolean, true if just created, false if already existed
            hd, hd_created = Thumbnail.objects.get_or_create(product=instance, type='hd')
            sd, sd_created = Thumbnail.objects.get_or_create(product=instance, type='sd')
            micro, micro_created = Thumbnail.objects.get_or_create(product=instance, type='micro')

            media_path = instance.media.name
            owner_slug = instance.slug

            if hd_created:
                helpers.create_thumbnail(media_path, hd, owner_slug, 'hd')

            if sd_created:
                helpers.create_thumbnail(media_path, sd, owner_slug, 'sd')

            if micro_created:
                helpers.create_thumbnail(media_path, micro, owner_slug, 'micro')

        # This DOES NOT work! It just saves multiples and continues  :-/
        # but at least it doesnt crash
        except MultipleObjectsReturned:
            print('ERROR detected')
            return HttpResponse('You can only have one of each type of thumbnail', status=403)

post_save.connect(product_post_save_receiver, sender=Product)
# There are also actions available for delete and init

tags/models.py
from django.db import models as m
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from django.db.models.query import QuerySet

from products.models import Product


class ActiveTagManager(m.Manager):
    def get_queryset(self):
        return super(ActiveTagManager, self).get_queryset().filter(active=True).order_by('title')


# this is redundant, but just for illustration
# how to make a dynamic queryset
# Tag.objects.all().active()
class ActiveTagQuerySet(QuerySet):
    def active(self):
        return self.filter(active=True)


class TagManager(m.Manager):
    def get_queryset(self):
        return ActiveTagQuerySet(self.model, using=self.db)

    # the point of this whole exercise is that it lets us apply .active() filter! :-/
    def all(self, *args, **kwargs):
        return super(TagManager, self).all(*args, **kwargs).active()


class Tag(m.Model):
    title = m.CharField(max_length=120, unique=True)
    slug = m.SlugField(blank=True, unique=True)
    products = m.ManyToManyField(Product, blank=True)
    active = m.BooleanField(default=True)

    # We need to explicitly define the default manager or it wont be used
    # It also has to be first to be default!!!
    # https://docs.djangoproject.com/en/1.10/topics/db/managers/#default-managers
    objects = m.Manager()

    # This will allow us to use Tags.active_tags.all() etc type of queries :)
    active_tags = ActiveTagManager()

    tags = TagManager()

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        view_name = 'tags:detail'
        # print('The absolute URL is:', reverse(view_name, kwargs={'slug': self.slug}))
        return reverse(view_name, kwargs={'slug': self.slug})


def tag_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)

pre_save.connect(tag_pre_save_receiver, sender=Tag)

products/forms.py
from django import forms
from .models import Product
from django.utils.text import slugify

AVAILABILITY_CHOICES = ((True, 'Yes'), (False, 'No'))  # tuple for all choice options


# Now we will create a from from a model!
class ProductModelForm(forms.ModelForm):

    # We can also define fields/widgets manually here -> helps keep the code style consistent with the 'manual' form
    tags = forms.CharField(label='Tags', required=False)
    is_available = forms.ChoiceField(label='Is available for sale', widget=forms.RadioSelect,
                                     choices=AVAILABILITY_CHOICES, initial=True)

    description = forms.CharField(label='', required=False, widget=forms.Textarea(
                                          attrs={
                                              'placeholder': 'Description ...',
                                              'cols': '30',
                                              'rows': '5',
                                          }))
    media = forms.FileField(label='', required=False, widget=forms.ClearableFileInput())

    class Meta:
        model = Product
        fields = [
            'title',
            'description',
            'price',
            'sale_price',
            'is_available',
            'media'
        ]

        # Or widgets can be defined here, however cant pass all the params as easily here
        widgets = {
            'title': forms.TextInput(
                  attrs={'placeholder': 'Product Title'}
            ),
            'price': forms.TextInput(
                attrs={'placeholder': 'Price'}
            ),
        }

    # def clean(self, *args, **kwargs):
    #     cleaned_data = super(ProductModelForm, self).clean(*args, **kwargs)
    #     title = cleaned_data.get('title')
    #     slug = slugify(title)
    #     slug_exists = Product.objects.filter(slug=slug).exists()
    #     if slug_exists:
    #         raise forms.ValidationError(
    #             'Product with this title already exists. Please try again')
    #     return cleaned_data

    # The same validation methods work here!
    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price <= 1:
            raise forms.ValidationError('Price must be higher than $1')
        elif price >= 100:
            raise forms.ValidationError('Price must be less than $100')
        else:
            return price

    # this function HAS to be called clean_(valid attribute name) or it doesnt apply!
    def clean_title(self):
        title = self.cleaned_data.get('title')
        if len(title) < 5:
            raise forms.ValidationError('Title must be 5 characters or longer')
        else:
            return title


# Here is a creating all the fields in the form manually
class ProductAddForm(forms.Form):
    title = forms.CharField(label='Product Title')
    description = forms.CharField(label='',
                                  widget=forms.Textarea(
                                      attrs={                              # empty label to not show any description
                                        'class': 'my-custom-class',
                                        'placeholder': 'Description ...',  # passing HTML attributes as a dictionary
                                        'cols': '30',
                                        'rows': '5',
                                        'some-attribute': 'some-value',  # can pass anything you want!
                                        }
                                  ))

    price = forms.DecimalField()
    # available = forms.ChoiceField(choices=AVAILABILITY_CHOICES)  # default option is drop-down menu
    is_available = forms.ChoiceField(label='Is available for sale',
                                     widget=forms.RadioSelect,
                                     choices=AVAILABILITY_CHOICES,
                                     initial=True)  # initial is the default value!

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price <= 1:
            raise forms.ValidationError('Price must be higher than $1')
        elif price >= 100:
            raise forms.ValidationError('Price must be less than $100')
        else:
            return price

    # this function HAS to be called clean_(valid attribute name) or it doesnt apply!
    def clean_title(self):
        title = self.cleaned_data.get('title')
        if len(title) < 5:
            raise forms.ValidationError('Title must be 5 characters or longer')
        else:
            return title

templates/products/product_detail.html
{% extends 'base.html' %}

{% load get_thumbnail %}


{% block content %}


    {{ block.super }}   {# we are importing the content #}
                        {# from the parent's block! #}

{# Purchase dialog #}
<script xmlns="http://www.w3.org/1999/html">
$(document).ready(function(){

{% block jquery %}

    {# Display current rating   #}
    $(".rating input[value='{{ my_rating }}']").attr("checked", "checked");

    {# Save new rating value  #}
    $(".rating input[type='radio']").click(function() {
        var inputValue = $(this).val();
        console.log(inputValue);
        var request = $.ajax({
            url: "{% url 'products:rating' %}",
                        method: 'POST',
                        data: {
                            product_id: "{{ object.id }}",
                            rating_value: inputValue
                        }
                    });
        request.done(function (data) {
            console.log('User {{ request.user }} rated {{ object.slug }}');
            console.log(data.success)
        });

        request.fail(function (errorThrown) {
            alert('Your rating could not be saved!');
            console.log(errorThrown);
            console.log(errorThrown.responseText)
        })
    });


    {# Carry out product purchase #}
    $('#purchase-btn').click(function (event) {
        event.preventDefault();
        var purchaseBtn = $(this);
        $('#dialog-confirm').fadeIn('300');
        $('#dialog-confirm').dialog({
            resizable: false,
            height: 220,
            width: 350,
            modal: true,
            buttons: {
                1: {
                    id: 'confirm',
                    text: 'Confirm',
                    click: function () {
                        console.log('Purchase confirmed');
                         var request = $.ajax({
                            url: "{% url 'checkout' %}",
                            method: 'POST',
                            data: {
                                product_id: "{{ object.id }}"
                            }
                        });

                        request.done(function (data) {
                            console.log('Purchased {{ object.slug }}, product ID {{ object.id }}');
                            console.log(data.time);

                            var removeButton = purchaseBtn.fadeOut(500);
                            var links = (
                                    '<p>Purchase Successful!<p><br>'
                                    + '<p><a href="{{ object.get_download }}?preview=True">Full Size Preview </a></p>'
                                    + '<form action="{{ object.get_download }}">'
                                    + '<input type="submit" value="Download Media" />'
                                    + "</form>");
                           removeButton.after($(links))


                        });

                        request.fail(function (errorThrown, textStatus, jqXHR) {
                            if (errorThrown.status == 403) {
                                alert('You must be logged in to make purchases')
                                }
                            else if (errorThrown.status == 500) {
                                alert('Sorry, something went wrong with the purchase.\n\n' +
                                        'Please contact IT support')
                                }
                            else {
                                alert(errorThrown.statusText)
                            }
                            console.log(jqXHR);
                            console.log(errorThrown);
                            console.log(textStatus)
                        });

                        $(this).dialog('close')
                    },
                    class: 'buy-btn' {# we add classes to identify this and add custom css to buttons #}
                },
                2: {
                    id: 'cancel',
                    text: 'Cancel',
                    click: function () {
                        $(this).dialog('close')
                    },
                    class: 'cancel-btn'
                }
            }
        })
    });
{% endblock jquery %}
})
</script>


    <h1>{{ greeting }}</h1>
    {#  object is a variable for DetailView class  #}

    <div class="col-primary pull-left">
        <h3>Product: {{ object }}</h3>
        <i>{{ object.description }}</i>
        {% if object.tag_set.all %}
            <p>Tags: {% for tag in object.tag_set.all %}
                {% if tag.active %}
                    <a href="{{ tag.get_absolute_url }}"><i><strong>{{ tag }}</strong></i></a>,
                {% endif %}
            {% endfor %}</p>
        {% endif %}

        {% if object.is_available %}
            {% if object.on_sale %}
                <div id="on-sale"><h3>ON SALE!!!</h3></div>
                <p>Price: ${{ object.sale_price }}</p>
            {% else %}
                <p>Price: ${{ object.price }}</p>
             {% endif %}
         {% else %}
            <div id="unavailable"><h3>Currently Unavailable</h3></div>
        {% endif  %}

        {% if object.transaction_set.count > 0 %}
            <br>
            <p>Purchased <strong>{{ object.transaction_set.count }}</strong> times</p>
        {% endif %}

        {% if rating_stats.rating__count > 0 %}
            <p>Rated <span style="color:darkgreen; font-weight:bold;">
                    *{{ rating_stats.rating__avg|floatformat }}*</span>
                by <strong>{{ rating_stats.rating__count }}</strong> users</p>
        {% endif %}
        <br>

        {% if  object.thumbnail_set.count > 0 %}
            <h3>Product Thumbnails</h3>
            {% for thumb in object.thumbnail_set.all %}
                <p>{{ thumb.type|upper }}: {{ thumb.height }} x {{ thumb.width }}</p>
                <img src="{{ thumb.media.url }}"/>
                <br>
            {% endfor %}
        {% else %}
            <br>
            <img src="{{ coming_soon|get_thumbnail:'sd' }}">
            <br>
        {% endif %}

        <br>
        {# Show the edit option for product owners and managers  #}
        {% if allowed_to_edit %}
            <form action="{% url 'products:edit' object.id %}">
                <input type="submit" value="Edit Product" />
            </form>
        {% endif %}
    </div>

    <div class="col-sidebar pull-right">
        {# Media has to exist #}
        {# User has to be authenticated to rate and purchase #}
        {# And has to have this product in his products to see the download/preview links #}

        {% if request.user.is_authenticated %}
            {% if object.media and object in request.user.myproducts.products.all %}

                <div id="download-links">
                    <p><a href="{{ object.get_download }}?preview=True">Full Size Preview </a></p>

                    {#  object.get_download here is the same as {% url 'products:download' object.id %} #}
                    <form action="{{ object.get_download }}">
                        <input type="submit" value="Download Media" />
                    </form>
                    <br>
                </div>

            {% elif object.media %}
    {#            <p><a id="purchase-btn" href="#">Purchase</a></p>#}
                <p><a id="purchase-btn" class="btn btn-primary btn-lg" href="#" role="button">Purchase</a></p>
                <div id="dialog-confirm" title="Confirm Purchase" style="display:none">
                    <p>Your card on file will be charged</p>
                    <p>Please confirm this purchase</p>
                </div>

            {% endif %}

            <br>
            {% include 'products/product_rating_snippet.html' %}

        {% else %}
            <br>
            <p>Please log in to purchase and rate</p>

        {% endif %}

    </div>


    <div class="clearfix"></div>

    <a href="{% url 'products:list' %}"><br> <<< Back to Product List</a>

{% endblock %}

templates/products/product_list.html
{% extends 'base.html'%}
{% load get_thumbnail %}


{% block content %}

<div id="search-box">

    <h3>Search Products</h3>
    <h4>By Title, Description or Tags</h4>

    <form method="GET" action="">
        <input type="text" name="td" value="{{ request.GET.td }}">
        <input type="submit" value="Search"> <br>
    </form>

    <h4>Within a Price Range</h4>
    <form method="GET" action="">
        From <input type="number" name="pf" min="1" max="1000" value="{{ request.GET.pf }}">
        To <input type="number" name="pt" min="1" max="1000" value="{{ request.GET.pt }}">
        <input type="submit" value="Find"> <br>
    </form>
</div>

<h1>Products</h1>
<ul>

    {#  object_list is a  built-in variable for ListView class #}
    {% for instance in object_list %}
        {% if instance.is_available == True %}
            {# cycle will go through the list of agrs and apply the next one each tims its called #}
            {# ie here each class is assigned a different color :) #}
            <div class="{%  cycle 'a' 'b' 'c' %}">
            <li><h4>{{ instance }}</h4></li>
            {% if instance.media %}
                <a href="{% url 'products:detail_slug' instance.slug %}">
                    <img src="{{ instance|get_thumbnail:'micro' }}"/></a>
            {% else %}
                <a href="{% url 'products:detail_slug' instance.slug %}">
                <img src="{{ coming_soon|get_thumbnail:'micro' }}"/></a>
            {% endif %}
            <br>
            {% if instance.description %}
            <i><strong>{{ instance.description|capfirst|truncatewords:5 }}</strong></i><br>
            {% endif %}
            ${{ instance.price }}
            {# A stupid 'with' example  #}
{#            {% with ':)' as smiley %}#}
{#                <br>{{ smiley }}#}
{#            {% endwith %}#}
            <br><br>
            </div>
        {%  endif %}
    {% empty %}
        <li>No Products have been registered yet</li>
    {% endfor %}
</ul>

{# Allow authenticated users to create new products   #}
{#{% if request.user.is_authenticated %}#}
{#    <form action="{% url 'sellers:add' %}">#}
{#        <input type="submit" value="Add a New Product" />#}
{#    </form>#}
{#{% endif %}#}

{% endblock %}

templates/products/product_list_snippet.html
{%  load get_thumbnail %}

{% for instance in product_list %}
     {% if instance.is_available and instance.media %}
        <li>
            <a href="{{ instance.get_absolute_url }}">{{ instance.title }} - ${{ instance.price }}</a><br>
             <a href="{{ instance.get_absolute_url }}">
                <img src="{{ instance|get_thumbnail:'micro' }}"/></a><br>

        </li>
    {%  endif %}
{% empty %}
    <li>No Products Yet</li>
{% endfor %}

templates/products/product_rating_snippet.html
<div class="rating">
    <p>Rate this product:</p>
    <input type="radio" id="star5" name="rating" value="5" /><label for="star5" title="Rocks!">5 stars</label>
    <input type="radio" id="star4" name="rating" value="4" /><label for="star4" title="Pretty good">4 stars</label>
    <input type="radio" id="star3" name="rating" value="3" /><label for="star3" title="Meh">3 stars</label>
    <input type="radio" id="star2" name="rating" value="2" /><label for="star2" title="Kinda bad">2 stars</label>
    <input type="radio" id="star1" name="rating" value="1" /><label for="star1" title="Sucks big time">1 star</label>
</div>

templates/products/user_library.html
{% extends 'base.html'%}
{% load get_thumbnail %}


{% block content %}

<div id="search-box">

    <h3>Search My Library</h3>

    <form method="GET" action="">
        <input type="text" name="q" value="{{ request.GET.q }}">
        <input type="submit" value="Search"> <br>
    </form>

</div>

<h1>My Products</h1>
<table class="table table-bordered">
    {#  object_list is a  built-in variable for ListView class #}
    {% for instance in object_list %}
        <tr>
            <td>{{ instance.title }}</td>
            <td>
            {% if instance.media %}
                    <a href="{% url 'products:detail_slug' instance.slug %}">
                        <img src="{{ instance|get_thumbnail:'micro' }}" style="max-width: 100px"/></a>
            {% else %}
                    <a href="{% url 'products:detail_slug' instance.slug %}">
                        <img src="{{ coming_soon|get_thumbnail:'micro' }}" style="max-width: 100px"/></a>
            {% endif %}
            </td>
            <td><a href="{{ object.get_download }}?preview=True">Preview</a></td>
        <td>
            <form action="{{ object.get_download }}"><input type="submit" value="Download"/></form>
        </td>
        </tr>
    {% empty %}
        <li>You have not registered any products yet</li>
    {% endfor %}
</table>

{# Allow authenticated users to create new products   #}
{#{% if request.user.is_authenticated %}#}
{#    <form action="{% url 'sellers:add' %}">#}
{#        <input type="submit" value="Add a New Product" />#}
{#    </form>#}
{#{% endif %}#}

{% endblock %}