digitalmarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from dashboard.views import DashboardView
from checkout.views import CheckoutTestView, CheckoutAjaxView
from products.views import UserLibraryView


urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^seller/', include('sellers.urls', namespace='sellers')),
    url(r'^checkout/$', CheckoutAjaxView.as_view(), name='checkout'),
    url(r'^test$', CheckoutTestView.as_view(), name='test'),
    url(r'^admin/', admin.site.urls),
    # url(r'^$', RedirectView.as_view(url='products/')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^tags/', include('tags.urls', namespace='tags')),
    url(r'^library/', UserLibraryView.as_view(), name='library'),

    ####################### Old function-based views, for reference #################################
    # url(r'^list/$', product_views.list_view, name='list_view'),
    # url(r'^create/$', product_views.create_view, name='create_view'),
    # url(r'^detail/(?P<object_id>\d+)/$', product_views.detail_view, name='detail_view'),
    # url(r'^detail/(?P<object_id>\d+)/edit/$', product_views.update_view, name='update_view'),
    # url(r'^detail/(?P<slug>[\w-]+)/$', product_views.detail_slug_view, name='detail_slug_view'),
    # url(r'^detail/$', product_views.detail_view, name='detail_view')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL)

products/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.ProductListView.as_view(), name='list'),
    url(r'^rate/$', views.ProductRatingAjaxView.as_view(), name='rating'),
    # url(r'^(?P<pk>\d+)/edit/$', views.ProductEditView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.ProductEditView.as_view(), name='edit_slug'),

    url(r'^(?P<pk>\d+)/$', views.ProductDetailView.as_view(), name='detail'),
    # the slug url should be below the PK one, to avoid not found errors
    # because the slug regex will match the PK as well
    url(r'^(?P<slug>[\w-]+)/$', views.ProductDetailView.as_view(), name='detail_slug'),

    url(r'^(?P<pk>\d+)/download/', views.ProductDownloadView.as_view(), name='download'),
    url(r'^(?P<slug>[\w-]+)/download/', views.ProductDownloadView.as_view(), name='download_slug'),
]

tags/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.TagListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', views.TagDetailView.as_view(), name='detail'),
]

products/forms.py
from django import forms
from .models import Product
from django.utils.text import slugify

AVAILABILITY_CHOICES = ((True, 'Yes'), (False, 'No'))  # tuple for all choice options


# Now we will create a from from a model!
class ProductModelForm(forms.ModelForm):

    # We can also define fields/widgets manually here -> helps keep the code style consistent with the 'manual' form
    tags = forms.CharField(label='Tags', required=False)
    is_available = forms.ChoiceField(label='Is available for sale', widget=forms.RadioSelect,
                                     choices=AVAILABILITY_CHOICES, initial=True)

    description = forms.CharField(label='', required=False, widget=forms.Textarea(
                                          attrs={
                                              'placeholder': 'Description ...',
                                              'cols': '30',
                                              'rows': '5',
                                          }))
    media = forms.FileField(label='', required=False, widget=forms.ClearableFileInput())

    class Meta:
        model = Product
        fields = [
            'title',
            'description',
            'price',
            'sale_price',
            'is_available',
            'media'
        ]

        # Or widgets can be defined here, however cant pass all the params as easily here
        widgets = {
            'title': forms.TextInput(
                  attrs={'placeholder': 'Product Title'}
            ),
            'price': forms.TextInput(
                attrs={'placeholder': 'Price'}
            ),
        }

    # def clean(self, *args, **kwargs):
    #     cleaned_data = super(ProductModelForm, self).clean(*args, **kwargs)
    #     title = cleaned_data.get('title')
    #     slug = slugify(title)
    #     slug_exists = Product.objects.filter(slug=slug).exists()
    #     if slug_exists:
    #         raise forms.ValidationError(
    #             'Product with this title already exists. Please try again')
    #     return cleaned_data

    # The same validation methods work here!
    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price <= 1:
            raise forms.ValidationError('Price must be higher than $1')
        elif price >= 100:
            raise forms.ValidationError('Price must be less than $100')
        else:
            return price

    # this function HAS to be called clean_(valid attribute name) or it doesnt apply!
    def clean_title(self):
        title = self.cleaned_data.get('title')
        if len(title) < 5:
            raise forms.ValidationError('Title must be 5 characters or longer')
        else:
            return title


# Here is a creating all the fields in the form manually
class ProductAddForm(forms.Form):
    title = forms.CharField(label='Product Title')
    description = forms.CharField(label='',
                                  widget=forms.Textarea(
                                      attrs={                              # empty label to not show any description
                                        'class': 'my-custom-class',
                                        'placeholder': 'Description ...',  # passing HTML attributes as a dictionary
                                        'cols': '30',
                                        'rows': '5',
                                        'some-attribute': 'some-value',  # can pass anything you want!
                                        }
                                  ))

    price = forms.DecimalField()
    # available = forms.ChoiceField(choices=AVAILABILITY_CHOICES)  # default option is drop-down menu
    is_available = forms.ChoiceField(label='Is available for sale',
                                     widget=forms.RadioSelect,
                                     choices=AVAILABILITY_CHOICES,
                                     initial=True)  # initial is the default value!

    def clean_price(self):
        price = self.cleaned_data.get('price')
        if price <= 1:
            raise forms.ValidationError('Price must be higher than $1')
        elif price >= 100:
            raise forms.ValidationError('Price must be less than $100')
        else:
            return price

    # this function HAS to be called clean_(valid attribute name) or it doesnt apply!
    def clean_title(self):
        title = self.cleaned_data.get('title')
        if len(title) < 5:
            raise forms.ValidationError('Title must be 5 characters or longer')
        else:
            return title

products/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.db.models import Avg, Count
from mimetypes import guess_type

from django.views.generic import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView

from products.models import Product, ProductRating, MyProducts
from products.forms import ProductAddForm, ProductModelForm
from tags.models import Tag
from analytics.models import TagView

from sellers.mixins import *
from digitalmarket.mixins import *
from products.mixins import *


################################### helper functions ###############################################
def process_tags(tags, item):
    # we read the tags field, and split it on commas
    tags_list = tags.split(',')
    # these are bad tags we don't want to use
    exceptions = ['', ' ']
    for tag in tags_list:
        if tag not in exceptions:
            # we then make sure each tag is added or already is in db
            # [0] is the tag itself as .get_or_create returns a tuple
            new_tag = Tag.objects.get_or_create(title=str(tag).strip())[0]
            # and we add the product that is being edited to the tag :)
            new_tag.products.add(item)


########################################## Class-Based Views :-) #########################################
class ProductCreateView(SellerAccountMixin, FormVarsMixin, CreateView):
    model = Product
    form_class = ProductModelForm
    template_name = 'product_form.html'
    # success_url = '/products'  # url to redirect to on successful submission

    # these come from FormVarsMixin
    form_title = 'New Product Form'
    submit_btn = 'Create Product'
    reset_btn = 'Clear form'

    def form_valid(self, form):
        seller = self.get_account()
        form.instance.seller = seller
        valid_data = super(ProductCreateView, self).form_valid(form)  # form_valid() saves the instance
        # By this point the product has already been saved to the DB
        # so we can add ManyToMany values, e.g add user to managers
        # form.instance.managers.add(seller)
        tags = form.cleaned_data.get('tags')
        if tags:
            process_tags(tags, form.instance)
        return valid_data

    # We only need to specify this if get_absolute_url() is not defined OR we want to overwrite it
    def get_success_url(self):
        return reverse('products:list')


class ProductEditView(ProductManagerEditMixin, FormVarsMixin, MultiSlugMixin, UpdateView):
    model = Product
    form_class = ProductModelForm
    template_name = 'product_form.html'
    # success_url = '/products'  # url to redirect to on successful submission
    form_title = 'Update Product'
    submit_btn = 'Save Changes'

    # this is for handling tags
    def get_initial(self):
        initial = super(ProductEditView, self).get_initial()
        print(initial)
        tags = self.get_object().tag_set.all()
        # we grab the already assigned tags and construct a comma-separated string from them
        # (we later break this list down into constituent tags when saving the changes ;))
        initial['tags'] = ', '.join([tag.title for tag in tags])
        return initial

    def form_valid(self, form):
        valid_data = super(ProductEditView, self).form_valid(form)
        tags = form.cleaned_data.get('tags')
        obj = self.get_object()
        # We remove all associated tags and add the set that is currently in the form(below)
        obj.tag_set.clear()
        if tags:
            process_tags(tags, obj)

        return valid_data

    # The rest is handled by ProductManagerEditMixin


class ProductDetailView(MultiSlugMixin, DetailView):
    model = Product
    # using product_detail.html template
    # Everything else managed by ProductManagerDetailMixin

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['coming_soon'] = Product.objects.get(slug='coming-soon')
        # Current product
        product_object = self.get_object()
        tags = product_object.tag_set.all()
        # Get statistics for previous ratings if any
        rating_stats = product_object.productrating_set.aggregate(Avg('rating'), Count('rating'))
        context['rating_stats'] = rating_stats

        if self.request.user.is_authenticated():
            if tags:
                for tag in tags:
                    tag_analytics_object = TagView.objects.add_count(self.request.user, tag)
            user_rating = ProductRating.objects.filter(user=self.request.user, product=product_object)
            # Get current user's rating if exists
            if user_rating.exists():
                context['my_rating'] = user_rating.first().rating
        return context


class ProductDownloadView(ProductManagerDetailMixin, MultiSlugMixin, DetailView):
    model = Product

    def get(self, request, *args, **kwargs):
        product_object = self.get_object()

        # https://docs.djangoproject.com/en/1.10/ref/request-response/#fileresponse-objects
        # https://docs.python.org/3/library/functions.html#open
        # NONE OF THIS WORKS OFF S3, FOR LOCAL FILES ONLY!!!
        # file_path = str(settings.MEDIA_URL + obj.media.name)
        # print(file_path)
        # wrapper is for handling large files efficiently, i.e without tying up lots of memory
        # file_wrapper = FileResponse(open(file_path, 'rb'))

        # Only allow users with the right permissions to download stuff
        if product_object in request.user.myproducts.products.all():

            # Try to guess the MIME type of the download or just force download if unknown
            guessed_type = guess_type(product_object.media.name)
            mimetype = 'application/force-download'
            if guessed_type:
                mimetype = guessed_type
            response = HttpResponse(product_object.media, content_type=mimetype)

            # if the request contains 'preview', don't download the file, attempt preview
            # The product details page will have a separate link for this
            if 'preview' not in request.GET:
                response['Content-Disposition'] = 'attachment; filename={}'.format(product_object.media.name)

            response['X-SendFile'] = str(product_object.media.name)

            print(response)
            return response
        else:
            return HttpResponse('You are not authorized to access this download', status=403)


class ProductListView(SearchMixin, ComingSoonMixin, ListView):
    model = Product

    # We will set things up to work with the default auto-generated template name:
    # product_list.html
    # template_name = 'list_view.html' - not needed anymore


class UserLibraryView(LoginRequiredMixin, ComingSoonMixin, ListView):
    model = MyProducts
    template_name = 'products/user_library.html'

    def get_queryset(self, **kwargs):

        search_query = self.request.GET.get('q')
        # qs = super(UserLibraryView, self).get_queryset()
        obj = MyProducts.objects.get_or_create(user=self.request.user)[0]
        qs = obj.products.all()
        if search_query:
            matching_tags = Tag.active_tags.filter(
                title__icontains=search_query)

            qs = qs.filter(
                Q(title__icontains=search_query) |
                Q(description__icontains=search_query) |
                Q(tag__in=matching_tags))
        print(qs)
        return qs.distinct().order_by('title')


# left this here as the search mixing uses the function from product mixins
class SellerProductListView(SellerSearchMixin, ComingSoonMixin, ListView):
    model = Product
    template_name = 'sellers/product_list_view.html'


class ProductRatingAjaxView(AjaxRequiredMixin, View):

    def post(self, request, *args, **kwargs):

        # This does nothing, as CSRF token is not passed for unauthed users!
        if not request.user.is_authenticated():
            return JsonResponse({}, status=401)
        user = request.user
        user_products = user.myproducts.products.all()
        product_id = request.POST.get('product_id')
        rating_value = request.POST.get('rating_value')
        print('product_id:', product_id, 'rating_value:', rating_value)
        exists = Product.objects.filter(id=product_id).exists()
        if not exists:
            return JsonResponse({}, status=404)

        try:
            product_object = Product.objects.get(id=product_id)
        except:
            product_object = Product.objects.filter(id=product_id).first()
        print('Product is:', product_object)

        try:
            new_rating = ProductRating.objects.get_or_create(user=user, product_id=product_id)[0]

        except ProductRating.MultipleObjectsReturned:
            new_rating = ProductRating.objects.filter(user=user, product_id=product_id).first()

        new_rating.rating = int(rating_value)
        if product_object in user_products:
            new_rating.verified = True
        new_rating.save()

        # Delete if not needed
        data = {'success': True}

        return JsonResponse(data)



############################# Function-based views ##################################################
def detail_view(request, object_id=None):
    # this will be visible in the console/logs!
    print("The request is {}.\nThe user is {}.\nAuthenticated: {}."
          .format(request, request.user, request.user.is_authenticated))

    # and we can use this right away!!
    if request.user.is_authenticated:
        greeting = 'Hello {}'.format(str(request.user).capitalize())
    else:
        greeting = 'I don\'t know you'

    product = get_object_or_404(Product, id=object_id)
    template = 'detail_view.html'
    context = {'greeting': greeting,
               'object': product,
               }

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>

    {# jQuery Core #}
    <script src="http://code.jquery.com/jquery-1.12.4.min.js"></script>
    {# jQuery UI #}
    <script src="http://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

    {# Custom JavaScript to manage CSRF for Ajax calls #}
    <script src="{% static 'js/js-cookie.js' %}"></script>
    <script src="{% static 'js/django-csrf.js' %}"></script>

</head>

    {#  Bootstrap stuff  #}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {#  End of Bootstrap stuff  #}

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" href="{% static 'css/rating.css' %}" />
<style>

    .greeting {
        clear: both;
        margin:auto;
    }


    div.on-sale {
        color: green;
    }


    .unavailable {
        color: red;
    }

    {#  this brings the contents of the page to the middle and makes it somewhat responsive  #}
    .main-content {
        width: 600px;
        margin: 0 auto;
        clear: both;
    }

    {# align navigation bar with the main content column #}
    .main-nav {
        width: 600px;
        margin: 10px auto;
    }

    {# display all items of the navigation bar inline #}
    .main-nav li {
        display: inline;
    }

    .first-nav {
        padding-left: 0px;
    }

    .pull-left {
        float: left;
    }

    .pull-right {
        float: right;
    }

    .col-primary {
        width: 65%;
    }

    .col-sidebar {
        width: 35%;
    }

    #purchase-btn {
        background: darkblue;
    }
    .clearfix {
        clear: both;
    }

    {# CSS to customize Purchase dialog buttons   #}
    button.buy-btn {
        border: 1px solid lawngreen !important;
        background: lawngreen !important;
    }

    button.buy-btn .ui-button-text {
        color: white;
    }

    button.cancel-btn {
        border: 1px solid red !important;
        background: red !important;
    }

    button.cancel-btn .button-txt {
        color: white;
    }

    .ui-widget-header {
        border: 1px solid white !important;
        background: white !important;;
    }

    {# we add an empty style block so that we can adjust it as needed later #}
    {% block style %}
    {% endblock %}
</style>

<body>

<nav class="main-nav">
    <ul class="pull-left first-nav">
        <li><a href="{% url 'dashboard' %}">Digital Marketplace</a></li>
    </ul>
    <ul class="pull-right">
        <li><a href="{% url 'products:list' %}">| Products</a></li>
        <li><a href="{% url 'tags:list' %}">| Tags</a></li>
        <li><a href="{% url 'library' %}">| Library</a></li>
        <li><a href="http://localhost:8000/admin">| Admin |</a></li>
    </ul>

</nav>

<div class="greeting">
    {% if request.user.is_authenticated %}
        <p>Hello, <strong>{{ request.user.username|capfirst }}</strong></p>
    {% else %}
        <p>Hello, please identify yourself</p>
    {% endif %}
</div>

<div class="main-content">
    {% block content %}

{#        <p>Im from da base</p>#}
    {% endblock content %}  {# the 'content' part is optional #}
</div>



{# Test pop-up #}
{#<script>#}
{#    $(document).ready(function(){#}
{#        alert("Page Loaded!");#}
{#    })#}
{#</script>#}
</body>

</html>

templates/create_view.html
{% extends 'base.html' %}

{% block content %}

    {#  here we are calling the form template without passing any varialbles #}
    {#  because they are aready passed form the create_view() function  #}
    {#  as long as the variable names match what the form expects this will work!  #}
    {% include 'product_form.html' %}

{% endblock %}

templates/list_view.html
{%  extends 'base.html' %}

{% block style %}
    h1 {
        color: green;
    }
{% endblock %}

{% block content %}
    <h1>List View</h1>
    <ul>
        {% for item in queryset %}
        <li>{{ item }}: {{ item.description }}  -  ${{ item.price }}</li>
        <br>
    {%  endfor %}
    </ul>
{% endblock %}


<h1>You cant see me!!!</h1> <!-- This is outside of HTML tag, so not parsed by the browser

templates/product_form.html
<form method="POST" action="">

        <h1>{{ form_title }}</h1>
        {% csrf_token %}
        {{ form.as_p }}
        {% if submit_btn %}
        <input type="submit" value="{{ submit_btn }}">
        {% endif %}
        {% if reset_btn %}
        <input type="reset" value="{{ reset_btn }}">
        {% endif %}
    </form>

templates/update_view.html
{% extends 'base.html' %}

{% block content %}

{#  Here we harcode the variables to be passed to the product_form  #}
{% include 'product_form.html' with form_title='Update Product Info' submit_btn='Save Changes' %}

{% endblock %}