digitalmarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from dashboard.views import DashboardView
from checkout.views import CheckoutTestView, CheckoutAjaxView
from products.views import UserLibraryView


urlpatterns = [
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^seller/', include('sellers.urls', namespace='sellers')),
    url(r'^checkout/$', CheckoutAjaxView.as_view(), name='checkout'),
    url(r'^test$', CheckoutTestView.as_view(), name='test'),
    url(r'^admin/', admin.site.urls),
    # url(r'^$', RedirectView.as_view(url='products/')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^tags/', include('tags.urls', namespace='tags')),
    url(r'^library/', UserLibraryView.as_view(), name='library'),

    ####################### Old function-based views, for reference #################################
    # url(r'^list/$', product_views.list_view, name='list_view'),
    # url(r'^create/$', product_views.create_view, name='create_view'),
    # url(r'^detail/(?P<object_id>\d+)/$', product_views.detail_view, name='detail_view'),
    # url(r'^detail/(?P<object_id>\d+)/edit/$', product_views.update_view, name='update_view'),
    # url(r'^detail/(?P<slug>[\w-]+)/$', product_views.detail_slug_view, name='detail_slug_view'),
    # url(r'^detail/$', product_views.detail_view, name='detail_view')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL)

products/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.ProductListView.as_view(), name='list'),
    url(r'^rate/$', views.ProductRatingAjaxView.as_view(), name='rating'),
    # url(r'^(?P<pk>\d+)/edit/$', views.ProductEditView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/edit/$', views.ProductEditView.as_view(), name='edit_slug'),

    url(r'^(?P<pk>\d+)/$', views.ProductDetailView.as_view(), name='detail'),
    # the slug url should be below the PK one, to avoid not found errors
    # because the slug regex will match the PK as well
    url(r'^(?P<slug>[\w-]+)/$', views.ProductDetailView.as_view(), name='detail_slug'),

    url(r'^(?P<pk>\d+)/download/', views.ProductDownloadView.as_view(), name='download'),
    url(r'^(?P<slug>[\w-]+)/download/', views.ProductDownloadView.as_view(), name='download_slug'),
]

sellers/urls.py
from django.conf.urls import url
from sellers import views as s_views
from products import views as p_views

urlpatterns = [

    url(r'^$', s_views.SellerDashboard.as_view(), name='dashboard'),
    url(r'^products/$', p_views.SellerProductListView.as_view(), name='product_list'),
    url(r'^products/add/$', p_views.ProductCreateView.as_view(), name='product_add'),
    url(r'^products/(?P<pk>\d+)/$', s_views.SellerProductDetailRedirectView.as_view()),
    url(r'^products/(?P<pk>\d+)/edit/$', p_views.ProductEditView.as_view(), name='product_edit'),
    url(r'^transactions/', s_views.SellerTransactionList.as_view(), name='transactions')
]

tags/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.TagListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', views.TagDetailView.as_view(), name='detail'),
]

billing/models.py
from django.db import models as m
from django.contrib.auth.models import User
from products.models import Product


# Create your models here.
class Transaction(m.Model):

    user = m.ForeignKey(User)
    product = m.ForeignKey(Product)
    price = m.DecimalField(max_digits=100, decimal_places=2)
    timestamp = m.DateTimeField(auto_now_add=True, auto_now=False)
    success = m.BooleanField(default=True)

    # To be added later
    # transaction_id_payment_system = Braintree / Stripe
    # payment_method
    # last_four (digits of the credit card)

    def __str__(self):
        return '{}----{}----{}--{}--{}'.format(self.id, self.timestamp, self.user, self.product, self.product.get_price)

sellers/models.py
from django.db import models as m
from django.contrib.auth.models import User


# Create your models here.

class SellerAccount(m.Model):
    user = m.ForeignKey(User)
    managers = m.ManyToManyField(User, related_name='manager_sellers', blank=True)
    # we want the seller accounts to be manually approved
    active = m.BooleanField(default=False)
    timestamp = m.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.user.username

sellers/forms.py
from django import forms


class NewSellerForm(forms.Form):

    agree = forms.BooleanField(label='Agree to Terms', widget=forms.CheckboxInput)

dashboard/views.py
from django.shortcuts import render
from django.views.generic import View
import random

from products.models import Product


class DashboardView(View):

    def get(self, request, *args, **kwargs):

        tag_views = None
        products = None
        top_tags = None
        #
        try:
            # get 5 tags most frequented by the given user
            tag_views = request.user.tagview_set.all().order_by('-count')[:5]
        except:
            tag_views = None

        try:
            owned = request.user.myproducts.products.all()
        except:
            owned = None

        print('tag views:', tag_views)
        if tag_views:
            top_tags = [x.tag for x in tag_views]

            # filter all products by tags that the user is interested in
            products = Product.objects.filter(tag__in=top_tags)
            if owned:
                # exclude already owned products from suggestions
                products = products.exclude(pk__in=owned)

            # if we have less than 10 suggestions
            # then pick 10 non-owned products from DB and offer those
            if products.count() < 10:
                # .order_by('?') is returing the queryset in random order
                products = Product.objects.all().order_by('?')
                if owned:
                    # exclude already owned products from suggestions
                    products = products.exclude(pk__in=owned)
                products = products[:10]
            else:
                # .distinct() = unique results :)
                products = products.distinct()
                # offer the products in random order every time
                products = sorted(products, key=lambda x: random.random())
        else:
            products = None
            top_tags = None

        context = {
            'products': products,
            'top_tags': top_tags
        }
        print(context)

        return render(request, 'dashboard/view.html', context)

sellers/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import View
from django.views.generic.list import ListView
from django.views.generic.base import RedirectView
from django.views.generic.edit import FormMixin

from sellers.mixins import SellerAccountMixin

from products.models import Product
from sellers.forms import NewSellerForm
from sellers.models import SellerAccount
from billing.models import Transaction


# Example of RedirectVIew in views
# https://docs.djangoproject.com/en/1.10/ref/class-based-views/base/#redirectview
class SellerProductDetailRedirectView(RedirectView):
    permanent = True

    def get_redirect_url(self, *args, **kwargs):
        obj = get_object_or_404(Product, pk=kwargs['pk'])
        return obj.get_absolute_url()


class SellerTransactionList(SellerAccountMixin, ListView):
    model = Transaction
    template_name = 'sellers/transaction_list_view.html'

    def get_queryset(self):
        transactions = self.get_transactions()
        return transactions

    def get_context_data(self, **kwargs):
        context = super(SellerTransactionList, self).get_context_data(**kwargs)
        context['total_sales'] = self.get_all_sales()
        context['sales_by_product'] = self.get_sales_by_product()
        context['sales_by_product'] = self.get_sales_by_product()
        return context


class SellerDashboard(SellerAccountMixin, FormMixin, View):
    form_class = NewSellerForm
    success_url = '/seller/'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get(self, request, *args, **kwargs):
        apply_form = self.get_form()  # NewSellerForm()
        account = self.get_account()
        context = {}

        # 3 possible options whe arriving to the sellers URL
        # if account does not exist, show form
        # if exists but not active, show pending
        # if exists and active, show dashboard

        # SellerAccountMixin will return account=None if no account found
        if account:

            if account.active:
                # get all seller's products and all transactions involving these products
                products = self.get_products()[:5]

                # rewrite this as a dictionary: context = {}
                context = {
                    'title': 'Seller Dashboard',
                    'products': products,
                    'transactions_today': self.get_transactions_today(),
                    'sales_today': self.get_sales_today(),
                    'recent_transactions': self.get_recent_transactions(5)
                    }
                # context['title'] = 'Seller Dashboard'
                # context['products'] = products
                # context['transactions_today'] = self.get_transactions_today()
                # context['recent_transactions'] = self.get_recent_transactions(5)
            # i.e. if not approved
            else:
                context['title'] = 'Account Pending Approval'

        # if account does not exist
        else:
            context['title'] = 'Register a New Seller Account'
            context['apply_form'] = apply_form

        return render(request, 'sellers/dashboard.html', context)

    def form_valid(self, form):
        valid_data = super(SellerDashboard, self).form_valid(form)
        print('Working')
        print(valid_data)
        obj = SellerAccount.objects.create(user=self.request.user)
        return valid_data

templates/sellers/dashboard.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ title }}</h1>

    {% if apply_form %}

    <form method="POST" action="">{% csrf_token %}
        <h3>Rules of the Marketplace</h3>
        <ol>
            <li>Only upload files you own</li>
            <li>Don't steal</li>
            <li>Blah blah blah</li>
            <li>Yada yada</li>
        </ol>

    {{ apply_form.as_p }}
        <br>
    <input type="SUBMIT" value="Continue"/>
    </form>

    {% endif %}

    {% if products %}
        <div class="pull-right col-sidebar">
            <h2>My Products</h2>
            <strong><a href="{% url 'sellers:product_list' %}">Manage</a></strong> |
            <strong><a href="{% url 'sellers:product_add' %}">Add Product</a></strong>
            <br>
            {# {% include 'sellers/product_add_snippet.html' %}#}
            <br>
            {% include 'products/product_list_snippet.html' with product_list=products %}
        </div>
    {% endif %}


    {# This should always exist as long as there is at least 1 transaction #}
    {% if recent_transactions %}
        <div class="pull-left col-primary">

            {% if transactions_today %}
                <h2>Today's Sales</h2>
                {% include 'sellers/transaction_list_snippet.html' with transaction_list=transactions_today time='detailed' %}

                <p><strong>Total Sales Todays: ${{ sales_today }}</strong></p>
                <br>
            {% endif %}

            <h2>Recent Transactions</h2>
            {% include 'sellers/transaction_list_snippet.html' with transaction_list=recent_transactions  time='since' %}

            <p>
                <a href="{% url 'sellers:transactions' %}">Transaction History and Sales Breakdown</a>
            </p>
        </div>
    {% endif %}




{% endblock %}

templates/sellers/product_add_snippet.html
    <div>
    <form action="{% url 'sellers:product_add' %}">
        <input type="submit" value="Add Product" />
    </form>
    </div>

templates/sellers/product_list_view.html
{% extends 'base.html'%}
{% load get_thumbnail %}


{% block content %}

<div id="search-box">

    <h3>Search Products</h3>
    <h4>By Title, Description or Tags</h4>

    <form method="GET" action="">
        <input type="text" name="td" value="{{ request.GET.td }}">
        <input type="submit" value="Search"> <br>
    </form>

    <h4>Within a Price Range</h4>
    <form method="GET" action="">
        From <input type="number" name="pf" min="1" max="1000" value="{{ request.GET.pf }}">
        To <input type="number" name="pt" min="1" max="1000" value="{{ request.GET.pt }}">
        <input type="submit" value="Find"> <br>
    </form>
</div>

<h1>Manage Products</h1>

    {% include 'sellers/product_add_snippet.html' %}
    <br>

<table class="table table-bordered">
    {#  object_list is a  built-in variable for ListView class #}
    {% for instance in object_list %}
        <tr>
            <td>{{ instance.id }}</td>
            <td>{{ instance.title }}</td>
            <td>
            {% if instance.media %}
                    <a href="{% url 'products:detail_slug' instance.slug %}">
                        <img src="{{ instance|get_thumbnail:'micro' }}" style="max-width: 100px"/></a>
            {% else %}
                    <a href="{% url 'products:detail_slug' instance.slug %}">
                        <img src="{{ coming_soon|get_thumbnail:'micro' }}" style="max-width: 100px"/></a>
            {% endif %}
            </td>
            <td>  ${{ instance.price }}  </td>
            <td>Available: {{ instance.is_available }}</td>
            <td><a href="{{ instance.get_edit_url }}">Edit</a></td>
        </tr>
    {% empty %}
        <li>You have not registered any products yet</li>
    {% endfor %}
</table>

{% endblock %}

templates/sellers/sales_by_product_snippet.html
<table class="table table-bordered">
    <thead>
        <th>Product</th>
        <th>Times Sold</th>
        <th>Total Sales</th>
    </thead>
    <tbody>
    {% for stat in sales_by_product %}
    <tr>
        {# This is super-pants :( #}
        <td>{{ stat.0 }}</td>
        <td>{{ stat.1 }}</td>
        <td>${{ stat.2 }}</td>
    </tr>
    {%  endfor %}
    </tbody>
</table>

templates/sellers/transaction_list_snippet.html
<table class="table table-bordered">
    <thead>
        <th>Product</th>
        <th>User</th>
        <th>Price</th>
        <th>Purchase Date</th>
    </thead>
    <tbody>
    {% for t in transaction_list %}
    <tr>
        <td>{{ t.product }}</td>
        <td>{{ t.user }}</td>
        <td>${{ t.price }}</td>
        {% if time == 'since' %}
            <td>{{ t.timestamp|timesince }}</td>
        {% elif time == 'detailed' %}
            <td>{{ t.timestamp|date:"SHORT_DATE_FORMAT" }} {{ t.timestamp|date:"H:i:s" }}</td>
        {% endif %}
    </tr>
    {%  endfor %}
    </tbody>
</table>

templates/sellers/transaction_list_view.html
{% extends 'base.html' %}

{% block content %}

{#    <div class="pull-left col-primary">#}

        <h1>Transaction History</h1>

            {% include 'sellers/transaction_list_snippet.html' with transaction_list=object_list time='detailed' %}

        <p><strong>Total Sales: ${{ total_sales }}</strong></p>

{#    </div>#}

{#    <div class="pull-right col-sidebar">#}
        <h1>Sales by product</h1>

            {% include 'sellers/sales_by_product_snippet.html' %}

{#    </div>#}
        <br><br>
        <a href="{% url 'sellers:dashboard' %}">Back to Seller Dashboard</a>
{% endblock %}